name: $(BuildDefinitionName).$(DayOfYear)$(Rev:.r)
trigger:
  batch: true
  branches:
    include:
    - master

# Don't trigger on PRs
pr: none

resources:
  repositories:
  - repository: pipelines
    type: github
    endpoint: github_services
    name: zloeber/azure-pipeline-library

stages:
## Build Hugo site (DEV)
- template: build/hugo-generate.yml@pipelines
  parameters:
    initialize: true
    baseurl: 'https://zacharyloeber-decks.onrender.com/'
    testhtml: 'true'
    outputpath: './testsite'
    contentpath: './content'
    drafts: 'true'
    target: 'dev'
    artifact: 'devartifact'
- template: deploy/git-folder.yml@pipelines
  parameters:
    repo: 'https://github.com/zloeber/deck.loeber.live.git'
    branch: 'master'
    path: 'testsite'
    environment: 'dev'
    target: 'dev'
    pipelineartifact: 'devartifact'

## Build Hugo site (PROD)
- template: build/hugo-generate.yml@pipelines
  parameters:
    initialize: true
    baseurl: 'https://deck.loeber.live/'
    testhtml: 'true'
    outputpath: './public'
    contentpath: './content'
    target: 'prod'
    artifact: 'prodartifact'
- template: deploy/git-folder.yml@pipelines
  parameters:
    repo: 'https://github.com/zloeber/deck.loeber.live.git'
    branch: 'master'
    path: 'public'
    environment: 'production'
    target: 'prod'
    pipelineartifact: 'prodartifact'
